#!/bin/bash

./mem2.bash&pid=$!    

echo -e "mem2.bash $pid\n" > result2
echo -e "top five for every iteration\n" > five_pid2

while true
do
	line=$(top -p $pid -b -n 1 | head -8 | tail -n +8)
	free=$(top -b -n 1 | head -4 | tail -n +4 | awk '{print ""$6""}')
	swap=$(top -b -n 1 | head -5 | tail -n +5 | awk '{print ""$5""}')
	line=$(echo -e $line | awk '{print ""$11" "$10" "$5" "$6" "$7" "$9""}')
	five=$(top -b -n 1 | head -12 | tail -n +8 | awk '{print ""$1""}' | paste -s -d ">")
	if ps -p $pid > /dev/null
	then
		result=$(echo -e "$line $free $swap\n")
		echo $result >> result2
		echo $five >> five_pid2
	fi
	
done


