#!/bin/bash
echo Menu
echo "1)open nano"
echo "2)open vi"
echo "3)open links"
echo "4)close Menu"
read chosen
case $chosen in
	1)
		nano
	;;
	2)
		vi
	;;
	3)
		links
	;;
	4)
		echo Paka
	;;
	*)
		echo Dich
		$0
esac
