#!/bin/bash
REPORT="$HOME/backup-report"

todayDate=$(date +"%Y-%m-%d")
todaySec=$(date -d "$todayDate" +"%s")
lastBackupDate=$(ls $HOME | grep -E "^Backup-" | sort -n | tail -1 | sed "s/Backup-//")
lastBackup="$HOME/Backup-$lastBackupDate"
lastBackupSec=$(date -d "$lastBackupDate" +"%s")

dateDiff=$(echo "($todaySec - $lastBackupSec) / 60 / 60 / 24" | bc)

if [[ ! -d $HOME/source ]]
then
	echo "ERROR"
	exit 1
fi


if (( $dateDiff > 7 )) || [[ -z "$lastBackupDate" ]]
then
	mkdir "$HOME/Backup-$todayDate"
	echo "Backup was created "$todayDate" in directory "$HOME". Copied files :" >> $REPORT
	for i in $(ls $HOME/source)
	do
		cp "$HOME/source/$i" "$HOME/Backup-$todayDate"
		echo -e "\n\t$i" >> $REPORT
	done	
else
	changes=""
	for file in $(ls $HOME/source)
	do
		if [[ -d "$HOME/source/$file" ]]
		then
			echo "ERROR - File is a Directory"
			rm -r $HOME/source/$1
			fi
		if [[ -f "$lastBackup/$file" ]]
		then
			source_size=$(stat $HOME/source/$file -c%s)
			actual_size=$(stat $lastBackup/$file -c%s)
			sizeDiff=$(echo "$source_size - $actual_size" | bc)

			if (( $sizeDiff != 0 ))
			then
				mv "$lastBackup/$file" "$lastBackup/$file.$todayDate"
				cp "$HOME/source/$file" $lastBackup
				changes="$changes\n\tFile $file updated. New version: $file.$todayDate."
			fi
		else
			cp "$HOME/source/$file" $lastBackup
			changes="$changes\n\tNew file $file copied"			
		fi
	done
	changes=$(echo $changes | sed 's/^\\n//')
	if [[ ! -z "changes" ]] 
	then
		echo -e "Backup ($lastBackupDate) was updated:\n$changes" >> $REPORT
	fi
fi
