#!/bin/bash
restoreDir="$HOME/restore"

lastBackupDate=$( ls $HOME | grep -E "^Backup-" | sort -n | tail -1 | sed 's/^Backup-//')
lastBackup="$HOME/Backup-$lastBackupDate"

if [[ -z "$lastBackupDate" ]]
then
	echo "backups doesn't exist"
	exit 1
fi

if [[ ! -d "$restoreDir" ]]
then
	mkdir $restoreDir
else
	rm -r $restoreDir
	mkdir $restoreDir
fi

for file in $(ls $lastBackup | grep -Ev "\.[0-9]{4}-[0-9]{2}-[0-9]{2}$")
do
	cp "$lastBackup/$file" "$restoreDir/$file"
done
