#!/bin/bash
result=1
operate='+'
tail -n 0 -f 5.in | while true
do
	read line
	case $line in
	'+')
		operate='+'
		echo "adding"
	;;
	'*')
		operate='*'
		echo "multiplying"
	;;
	[0-9]*)
		res=$result
		if [[ $operate == '+' ]]
			then
				let result=$result+$line
			else
				let result=$result\*$line
		fi
		echo "$res $operate $line = $result"
	;;
	*)
		echo "ERROR"
	;;
	esac
done
