#!/bin/bash
name=$(date '+%d.%m.%y_%H:%M:%S')
mkdir ~/test && echo "catalog test was successfully" >> ~/report.tmp && touch ~/test/$name.tmp
ping -c 1 www.net_nikogo.ru || echo "ERROR" >> ~/report.tmp
